### ISSUE TITLE
Top menu is not diplayed

### ISSUE THREAD

**Issue by julienrott** [zjedi/hugo-scroll#143]
Hi,

The top menu is not displayed on mobile when scrolling down.
Can you fix this or tell me how it is managed, so I can try to fix it and create a PR ?

Thanks.

**Comment by zjedi** [comment]
Hi, what phone / browser do you use? Would you know what is the screen resolution reported from the browser?

**Comment by julienrott** [comment]
I use safari on an IPhone SE. I just noticed that it works in landscape mode but not in portrait mode.
But it is reproducible with DevTools in chrome too.

**Comment by zjedi** [comment]
I belive it will have to do with this
```css
@media only screen and (max-width: 500px) {
  .fixed-nav {
    display: none;
  }
```
https://github.com/zjedi/hugo-scroll/blob/master/assets/css/responsiveness.scss#L91

You can try removing `display: none`, that should fix it.
